### ISSUE TITLE
Auto Reload in Linux

### ISSUE THREAD

**Issue by karasaj** [everettsouthwick/amazon-auto-reload#16]
Hi,

Wanted to ask; have you managed to test the Node.js code in Linux yet? I still haven't quite been able to get it running in Linux, but I have been using the Python successfully (I know the old python branch was written for windows). 

If you haven't tested it in Linux, or you have and it isn't working for you either, I can update a branch with linux support in Python (I'm more familiar with Python anyways). If you have tested it in Linux and find that it works fine, I'll go back to figuring out what's going on with my Raspberry Pi (could just because it is ARM64 instead of x86-64).

**Comment by everettsouthwick** [comment]
My daily driver is running elementary OS, so I'm sure it is compatible with Linux. It can't be run headless, however. So if your Raspberry Pi doesn't have a display it may run into issues. I think that's a limitation of Selenium and Amazon's website... I haven't really been able to track down a root cause. Could you try it on a machine with a display? You may also have to update the file path in some of the Typescript configuration files to use the Linux file system slashes (/ instead of \).

**Comment by karasaj** [comment]
Good to know, thanks. That is interesting, then. My Raspberry Pi is actually display enabled (I've been running non headless with the python version; it's just hooked up behind my normal computer setup), so it shouldn't be a headless problem (it's running with the proper chromedriver and selenium running in Python).

Just to confirm, you have an x86 based machine right? I wonder if it might have something to do with the selenium or chromedriver modules supported in Linux+ARM64.

**Comment by everettsouthwick** [comment]
Yeah I'm on an x86 based machine. Are you getting a specific error output when you try running it?

**Comment by ab763** [comment]
@karasaj: In case it helps, I also got the app working within a Docker container - see the #Docker section of the README.md for more - although I haven't tested it in Docker in about a month.

**Comment by karasaj** [comment]
Yes, here's what I got (sorry for the delay):

1 verbose cli [ '/repos/nvm/versions/node/v10.16.0/bin/node',
1 verbose cli   '/repos/nvm/versions/node/v10.16.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle finance-transact@3.1.0~prestart: finance-transact@3.1.0
6 info lifecycle finance-transact@3.1.0~start: finance-transact@3.1.0
7 verbose lifecycle finance-transact@3.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle finance-transact@3.1.0~start: PATH: /repos/nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/repos/amazon-auto-reload/node_modules/.bin:/repos/nvm/versions/node/v10.16.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle finance-transact@3.1.0~start: CWD: /repos/amazon-auto-reload
10 silly lifecycle finance-transact@3.1.0~start: Args: [ '-c', 'node dist/index.js' ]
11 silly lifecycle finance-transact@3.1.0~start: Returned: code: 1  signal: null
12 info lifecycle finance-transact@3.1.0~start: Failed to exec start script
13 verbose stack Error: finance-transact@3.1.0 start: `node dist/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/repos/nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/repos/nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid finance-transact@3.1.0
15 verbose cwd /repos/amazon-auto-reload
16 verbose Linux 4.15.0-1032-raspi2
17 verbose argv "/repos/nvm/versions/node/v10.16.0/bin/node" "/repos/nvm/versions/node/v10.16.0/bin/npm" "start"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error finance-transact@3.1.0 start: `node dist/index.js`
22 error Exit status 1
23 error Failed at the finance-transact@3.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

In the NPM log. And then from the CLI:
13 verbose stack Error: finance-transact@3.1.0 start: `node dist/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/repos/nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/repos/nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid finance-transact@3.1.0
15 verbose cwd /repos/amazon-auto-reload
16 verbose Linux 4.15.0-1032-raspi2
17 verbose argv "/repos/nvm/versions/node/v10.16.0/bin/node" "/repos/nvm/versions/node/v10.16.0/bin/npm" "start"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error finance-transact@3.1.0 start: `node dist/index.js`
22 error Exit status 1
23 error Failed at the finance-transact@3.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

I tried the docker install once but I think I might have hit an issue. It might have been when I was still on a 32-bit OS though; I'll investigate this week.
