### ISSUE TITLE
Issue with selenium-webdriver server connection terminating early?

### ISSUE THREAD

**Issue by karasaj** [everettsouthwick/amazon-auto-reload#5]
Hi,

First, thanks for the script. If you have time to look at this, I'd greatly appreciate it. Have you ever seen any issues with the selenium-webdriver throwing an error and crashing like so?

I am running on a Raspberry Pi 3B+ on a pretty quick connection, and have a pretty simple config with just one card and one reload time.

/home/pi/repos/amazon-auto-reload/node_modules/selenium-webdriver/lib/promise.js:2626
        throw error;
        ^

Error: Server terminated early with status 2
    at earlyTermination.catch.e (/home/pi/repos/amazon-auto-reload/node_modules/selenium-webdriver/remote/index.js:252:52)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/home/pi/repos/amazon-auto-reload/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/home/pi/repos/amazon-auto-reload/node_modules/selenium-webdriver/chrome.js:761:15)
    at createDriver (/home/pi/repos/amazon-auto-reload/node_modules/selenium-webdriver/index.js:170:33)
    at Builder.build (/home/pi/repos/amazon-auto-reload/node_modules/selenium-webdriver/index.js:642:16)
    at start (/home/pi/repos/amazon-auto-reload/index.js:12:86)
    at Object.<anonymous> (/home/pi/repos/amazon-auto-reload/index.js:21:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)

**Comment by everettsouthwick** [comment]
It could be caused by the lack of a display on your Raspberry Pi? There is an issue with running this in a headless browser due to some constraints on Amazon that I haven't been able to find a solution to. I believe that could have something to do with your the error you're getting.

**Comment by karasaj** [comment]
I actually tried it first running connected to HDMI, so odd. Perhaps it's something particular about the Chromium installed on my Pi or something. I'll play around with it and try and get somewhere, unless you have any other initial ideas.

**Comment by everettsouthwick** [comment]
It's recently been refactored to move away from a local copy of chromedriver to instead use an npm package to establish the web driver. Does that fix your issue?

**Comment by ab763** [comment]
Thanks. The move to a version of chromedriver managed by npm (instead of manually installed) happened around April 28.

(Note that the current version looks for ./config/default.json instead of ./config.json (along with being a 'rewrite' into TypeScript, etc.) and also adds some console debug output.)

@karasaj If the issue still persists after updating/following the [Instructions in the current Readme](../), can you please also advise on your OS and Chrome versions? Thank you!

**Comment by karasaj** [comment]
Hi,
Looks like the npm managed version of Chromedriver is 64 bit Linux only. Raspberry Pi 3B+ is a 32-bit machine of course. I looked around, and the latest version of chromedriver I can actually use is 2.9, which is obviously ooooold.

My initial goal was to see if I could get this running on my Pi out of curiosity - it's a stock Raspberry Pi 3B+, which means I've got Raspbian 9 and I'm using Chromium v60.

I'll test this on Firefox in a moment. Using chromedriver 2.9 (which shouldn't even support my version of Chromium, so I think it makes sense), I'm still getting an error, but with some more debug:

> amazon-auto-reload@2.0.0 start /home/pi/repos/amazon-auto-reload
> node dist/index.js

debug: App started {"ms":"+0ms"}
debug: Planning/working to make a purchase using **** ending in ****. {"ms":"+13ms"}
debug: Building a new chrome browser. {"ms":"+3ms"}
debug: Browser built. {"ms":"+78ms"}
info: completeTransactions is set to true. {"ms":"+1ms"}
debug: About to load https://smile.amazon.com/asv/reload/ {"ms":"+9ms"}
/home/pi/repos/amazon-auto-reload/node_modules/selenium-webdriver/lib/promise.js:2626
        throw error;
        ^

Error: Server terminated early with status 2
    at earlyTermination.catch.e (/home/pi/repos/amazon-auto-reload/node_modules/selenium-webdriver/remote/index.js:252:52)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/home/pi/repos/amazon-auto-reload/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/home/pi/repos/amazon-auto-reload/node_modules/selenium-webdriver/chrome.js:761:15)
    at createDriver (/home/pi/repos/amazon-auto-reload/node_modules/selenium-webdriver/index.js:170:33)
    at Builder.build (/home/pi/repos/amazon-auto-reload/node_modules/selenium-webdriver/index.js:642:16)
    at new Browser (/home/pi/repos/amazon-auto-reload/dist/browser.js:15:82)
    at new Site (/home/pi/repos/amazon-auto-reload/dist/site.js:8:24)
    at new Amazon (/home/pi/repos/amazon-auto-reload/dist/amazon.js:9:9)
    at amazonReload (/home/pi/repos/amazon-auto-reload/dist/index.js:38:20)
    at start (/home/pi/repos/amazon-auto-reload/dist/index.js:27:11)
    at Object.<anonymous> (/home/pi/repos/amazon-auto-reload/dist/index.js:51:1)

I'll try this on Firefox in a moment, because I think geckodriver might have more up to date support.

**Comment by karasaj** [comment]
Seeing a similar problem on Firefox too. Will keep digging from my end.

**Comment by karasaj** [comment]
Thought I'd give an update on this. I got busy for most of May and only recently got back to it. I reinstalled 64-bit Ubuntu Mate onto my Raspberry Pi 3B+ so that I'd have a 64-bit OS to work with. I'm still, at the moment, seeing an unhandled promise rejection warning when I attempt to use NodeJS with the basic instructions, but I was able to get it running using the old deprecated python version after directly installing chromedriver.

I'll see if I have time to figure out why it doesn't work on Node so that I can get back to master, but as of now I at least have a working version!

**Comment by karasaj** [comment]
Looks to be a separate issue; my initial one is solved - don't run this on 32bit linux!

**Comment by ab763** [comment]
Thank you. I had attempted to troubleshoot this last month by testing on the closest docker machine image that I could find to what you were running, but I had trouble getting even node/npm working in docker due to differences in the machine architecture from my Windows host. (I didn't test on my MacOS.)
